# No new line between shell prompts
add_newline = false

# No line-break between shell prompts
[line_break]
disabled = true

[java]
disabled = true

[git_status]
disabled = true

[username]
disabled = true
